spin_manifest_version = "1"
authors = ["Jonas Hecht <jonas.hecht@codecentric.de>"]
description = ""
name = "hello-typescript"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "hello-typescript"
source = "target/spin-http-js.wasm"
exclude_files = ["**/node_modules"]
[component.trigger]
route = "/..."
[component.build]
command = "npm run build"
